sonar.projectKey=myapp
sonar.projectName=MyApp Full-Stack
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/venv/**

sonar.python.version=3.12
sonar.javascript.node.maxspace=4096

sonar.sourceEncoding=UTF-8
